### ISSUE TITLE
[EPIC] Proposal Wizard

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#13]
**Is your feature request related to a problem? Please describe.**

**Wireframes**
[https://projects.pokecode.net/letterbox](https://link.getmailspring.com/link/AA810C27-EE24-47AC-B211-DEE6E797A4A9@getmailspring.com/0?redirect=https%3A%2F%2Fprojects.pokecode.net%2Fletterbox&recipient=cGF1QHBva2Vjb2RlLm5ldA%3D%3D)

**Acceptance criteria**
- [ ] Create a module

**Related issues**

- [x] #17 
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/9
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/10
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/11
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/8
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/7
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/14
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/15
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/16
- [x] https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/4

**Technical specifications**
https://github.com/openpoke/decidim-module-reporting-proposals/issues/4

**Implementation**
- [x] https://github.com/openpoke/decidim-module-reporting-proposals/pull/5

**Comment by SandrineGis** [comment]
@paarals we`re opting for nr 2 of the proposal wizard. Step 1 should start with "category" (mandatory), then Image, then adress/position, then title and then body. Step 3 can be deleted. @Naadjjaa fyi.

**Comment by paarals** [comment]
> @paarals we`re opting for nr 2 of the proposal wizard. Step 1 should start with "category" (mandatory), then Image, then adress/position, then title and then body. Step 3 can be deleted. @Naadjjaa fyi.
you can see new proposal here: [https://projects.pokecode.net/letterbox](https://link.getmailspring.com/link/AA810C27-EE24-47AC-B211-DEE6E797A4A9@getmailspring.com/0?redirect=https%3A%2F%2Fprojects.pokecode.net%2Fletterbox&recipient=cGF1QHBva2Vjb2RlLm5ldA%3D%3D)
